version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: sky-mysql
    restart: always
    environment:
      MYSQL_DATABASE: sky_take_out
      MYSQL_ROOT_PASSWORD: ${MY_DB_PASS}
    volumes:
      - /root/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    image: sky-take-out:local
    container_name: sky-take-out
    restart: always

    network_mode: host # 保持你原来的 host 模式
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/sky_take_out?serverTimezone=Asia/Shanghai&useSSL=false
      - MY_DB_USER=${MY_DB_USER}
      - MY_DB_PASS=${MY_DB_PASS}