spring:
  datasource:
    druid:
      # 直接写完整的 URL，虽然看起来长，但清晰且互不干扰
      url: jdbc:mysql://1.94.238.104:3306/sky_take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: +s6CCmAiDGcJpk3W
  redis:
    host: 1.94.238.104
    port: 6379
    password: mdaxXVQzMhGKWXQV
    database: 0
# 自定义业务配置
sky:
  minio:
    endpoint: http://1.94.238.104:9000
    access-key: admin
    secret-key: ggbondyingxiong
    bucket-name: sky-take-out
  wechat:
    appid: wx7d9d0bcad4d65d26
    secret: e5f3cca0f190f8ef952e8e23c953ea19
