server:
  port: 8080

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ${MY_REDIS_PASS}  # <--- 这里引用 Redis 专用密码
      database: 0

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    port: 3306
    database: sky_take_out
    username: root
    password: ${MY_DB_PASS}     # <--- 这里引用 数据库 专用密码
  minio:
    endpoint: http://1.94.238.104:9000
    access-key: admin
    secret-key: ggbondyingxiong
    bucket-name: sky-take-out